# Generated by Django 6.0.7 on 2026-08-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0003_note_content_note_created_at_note_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='updated_at',
        ),
    ]
