# Generated by Django 6.0.7 on 2026-08-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0004_remove_note_content_remove_note_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(),
        ),
    ]
