# Generated by Django 6.0.7 on 2026-08-17 21:09

import django.core.validators
import user_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=100, unique=True, validators=[user_app.validators.validate_user_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.EmailField(default=None, max_length=254, unique=True, validators=[django.core.validators.MinValueValidator(5, 'Ensure password is at least 5 characters long. Try again.'), django.core.validators.MaxValueValidator(200, 'Password cannot be longer than 200 characters. Try again.')]),
        ),
    ]
