# Generated by Django 6.0.7 on 2026-08-19 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('note_app', '0005_alter_note_title'),
        ('token_blacklist', '0013_alter_blacklistedtoken_options_and_more'),
        ('user_app', '0007_rename_user_appuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUser',
            new_name='User',
        ),
    ]
