# Generated by Django 6.0.7 on 2026-08-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_rename_appuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=2000, unique=True),
        ),
    ]
