server {
    listen 80;
    listen [::]:80;
    server_name http-cat.duckdns.org;
    return 301 https://http-cat.duckdns.org$request_uri;
 }
 # Port 443 is the real server - server HTTPS

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name http-cat.duckdns.org;

# error accessing the files for the .pem files
    ssl_certificate /etc/letsencrypt/live/http-cat.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/http-cat.duckdns.org/privkey.pem;

    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;

    index index.html;

    location /api/{
        proxy_pass http://backend:8000/api/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }


}



# Old Nginx from before deployment:

# server {
#     listen 80 default_server;
#     listen [::]:80 default_server;

#     index index.html;

#     location /api/{
#         proxy_pass http://backend:8000/api/;

#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#     }

#     location / {
#         root /usr/share/nginx/html;
#         try_files $uri /index.html;
#     }

# }

# Below is a starter code for when I get my code's server name from aws

# server {
#     listen 80;
#     listen [::]:80;
#     server_name <whatever I decide to name my server >

#     return 301 https://< http-what-app.duckdns.org/ >$request_uri;
# }
# # Port 443 is the real server - server HTTPS

# server {
#     listen 443 ssl;
#     listen[::]:443 ssl
#     server_name <Whatever I decided to name it>;

#     ssl_certificate /etc/letsencrypt/live/< http-what-app >/<the file.pem>;
#     ssl_certificate_key /etc/letsencrypt/live/< http-what-app >/<privatekey>.pem;

#     ssl_session_timeout 1d;
#     ssl_session_cache shared:SSL:10m;
#     ssl_session_tickets off;

#     index index.html;

#     location /api/{
#         proxy_pass http://backend:8000/api/api;

#         proxy_http_version 1.1;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#     }

#     location / {
#         root /usr/share/nginx/html;
#         try_files $uri /index.html;
#     }


# }





