# Generated by Django 6.0.7 on 2026-09-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='title',
            field=models.CharField(default=''),
        ),
    ]
