# GitHub Action Workflow based off Cypress Documentation
name: Cypress Tests

on:
  
  pull_request:
    branches:
        - main

  push:
    branches:
        - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    # container:
    #   image: cypress/browsers:22.15.0
    #   options: --user 1001
    steps:
      # - name: Checkout repository
      # uses: actions/checkout@v7
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
            node-version: 24
            cache: npm
            cache-dependency-path: personal_proj_front/package-lock.json


      - name: Install Dependencies
        run: npm ci
        working-directory: personal_proj_front

      - name: execute cypress
        uses: cypress-io/github-action@v7
        with:
            browser: electron
           # browswer: chrome 
            start: npm run dev
            wait-on: http://localhost:5173/
   